server:
  port: 8080  # Server runs on port 8080
  domain: http://localhost:8080
  session:
    timeout: 30m
    cookie:
      same-site: Lax


spring:
  application:
    name: linas-deli-api  # Application name


  datasource:
    url: jdbc:mysql://localhost:3306/linas_db  # MySQL database URL
    username: root  # Read from environment variable
    password: 1234  # Read from environment variable
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Updates schema automatically (use validate/none in production)
    show-sql: true  # Logs executed SQL queries
    properties:
      hibernate:
        format_sql: true  # Formats SQL queries for readability


  servlet:
    multipart:
      enabled: true  # Enables file uploads
      max-file-size: 10MB
      max-request-size: 50MB

  mvc:
    static-path-pattern: /upload/**
  web:
    resources:
      static-locations:file:upload/

  mail:
    host: smtp.gmail.com
    port: 587
    username: 1223jsun@gmail.com
    password: tjrm crrf splz vkwv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
admin:
  email: 1223jsun@gmail.com




logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # Debug logs for web requests
    org.hibernate.SQL: DEBUG  # Logs executed SQL queries
    org.hibernate.type.descriptor.sql: TRACE  # Logs SQL parameter values
#    org.springframework.security : TRACE
#    org.springframework.security.web.context.SecurityContextPersistenceFilter: DEBUG


app:
  cors:
    allowed-origins:
      - "http://localhost:5173"  # 프론트엔드 개발 서버 URL





